### PR TITLE
Add pre-commit-config, isort, flake8, black

### PR DESCRIPTION
**Pull request by THATDONFC**
https://pre-commit.com/

### CODE REVIEW

**Comment by shauneccles** [comment]
That looks awesome, good work.

**Comment by THATDONFC** [comment]
In these latest commits I have done the following:

- Update conf.py to use existing consts.py variables
- Pinned version requirements for requirements-docs.txt as recommended by RTD
- Rename requirements_docs.txt to requirements-docs.txt and fix broken links
- Remove unnecessary "end-of-file-fixer" hook from pre-commit config
- Update devcontainer and Dockerfile to use current local version of the users repository
- Add docs developement to the tasks.json file to make documentation development easier

**Comment by THATDONFC** [comment]
I'm having some second thoughts about the new Dockerfile. Yeon changed the Dockerfile a bit in #179. Should the Dockerfile build LedFx from the latest dev branch on github or from the users local repository? I changed it to build from the local copy of the repository but now I'm not so sure that's what we want.

**Comment by shauneccles** [comment]
My thoughts are that for most people starting off playing with the branch they will git clone the whole repo.

That would mean the repo becomes their copy and they can alter it as they want.

I'm not sure if adding an extra step if they don't have a local copy already is worth it.

Any way of adding an argument if they want a custom directory as the docker file LedFx base directory?

Would make sense that if you git clone LedFx that it comes with the source included and the docker file works on the source included.

**Pull request closed without merging**
